
# 뭐크 플로우 이름
name: Github Action 실행 시켜보기

# main 이라는 branch에 push 될때 워크 플로우를 실행
on:
  push:
    branches:
      - main

# 하나의 워크 플로우는 1개 이상의 잡으로 구성되어 있어야 한다.
jobs:
  # job를 식별하기 위한 id (My-Deploy-Job)
  My-Deploy-Job:
    # 운영환경 : ubuntu-latest
    runs-on: ubuntu-latest
    # job에는 여러개의 step 구성될 수 있다.
    steps:
      - name: Hello World 찍기
        # 실제 코드 (실 작업), 명령어
        run: echo "Hello World"

      - name: 여러 명열어 문장 작성하기
        run:
          echo "Good"
          echo "Morning"

      - name: GitHub Action 에 저장되어 있는 변수 사용하기
        run:
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

      - name: 노출이 되면 안되는 값
        run:
          echo ${{ secrets.MY_NAME }}
          echo ${{ secrets.MY_AGE }}


