
# 뭐크 플로우 이름
name: Github Action 실행 시켜보기

# main 이라는 branch에 push 될때 워크 플로우를 실행
on:
  push:
    branches:
      - main

# 하나의 워크 플로우는 1개 이상의 잡으로 구성되어 있어야 한다.
jobs:
  # job를 식별하기 위한 id (My-Deploy-Job)
  My-Deploy-Job:
    # 운영환경 : ubuntu-latest
    runs-on: ubuntu-latest
    # job에는 여러개의 step 구성될 수 있다.
    steps:
      - name: Hello World 찍기
        # 실제 코드 (실 작업), 명령어
        run: echo "Hello World"


